FROM hhnk_jupyter3

# set password

RUN /home/jovyan/.jupyter/

RUN wget https://raw.githubusercontent.com/wietsevangerwen/docker/master/jupyter/jupyter_notebook_config.py -o /home/jovyan/.jupyter/

USER $NB_UID
