# The initial docker image to install all required packages. Installing the gdal package is quite cumbersome
# and therefore the image that is create with this image is used for further development. 

# Choose your desired base image 
# FROM jupyter/scipy-notebook:latest
FROM hhnk_jupyter3

USER $NB_USER

# Plotly depedencies
RUN apt-get install -y --no-install-recommends \
        wget \
        xvfb \
        libgtk2.0-0 \
        libxtst6 \
        libxss1 \
        libgconf-2-4 \
        libnss3 \
        libasound2

# Install python3 libraries
# RUN conda install anaconda
RUN conda install -c conda-forge netCDF4 threedigrid tqdm apscheduler folium qgrid line_profiler plotly rasterio
RUN conda install -c conda-forge geopandas python=3.7 && \
      fix-permissions $CONDA_DIR

RUN pip install --upgrade pip threedigrid
RUN pip install ipython=='7.1' pyproj=='1.9.6' jupyter_contrib_nbextensions threedi_scenario_downloader && \
      fix-permissions /home/$NB_USER
      
# RUN jupyter contrib nbextension install #no permissions
      
# netCDF4 threedigrid tqdm apscheduler folium ipython=='7.1' qgrid

# openpyxl fiona==1.8a1 descartes xlrd xlwt && \
#    plotly lizard_connector 


# USER $NB_USER
