FROM hhnk_jupyter3

# set password

# RUN /home/jovyan/.jupyter/
RUN rm /home/jovyan/.jupyter/jupyter_notebook_config.py.1
RUN rm /home/jovyan/.jupyter/jupyter_notebook_config.py.2

RUN wget https://raw.githubusercontent.com/wietsevangerwen/docker/master/jupyter/jupyter_notebook_config.py /home/jovyan/.jupyter/

USER $NB_UID
