FROM hhnk_fews

USER root

# set password
# RUN rm /home/jovyan/.jupyter/jupyter_notebook_config.py
RUN wget https://raw.githubusercontent.com/wietsevangerwen/docker/master/jupyter/jupyter_notebook_config.py -P /home/jovyan/.jupyter/jupyter_notebook_config.py

USER $NB_UID
