# The initial docker image to install all required packages. Installing the gdal package is quite cumbersome
# and therefore the image that is create with this image is used for further development. 
# based on:https://github.com/plotly/orca/issues/150
# and: https://github.com/mathieuboudreau/orca-plotly-dockerfile/blob/master/Dockerfile
# Choose your desired base image 
FROM jupyter/scipy-notebook:latest

USER root

RUN apt-get update && apt-get install -y --no-install-recommends \
    unixodbc-dev \
    unixodbc \
    libpq-dev 
	
	
# Install python3 libraries
RUN conda update -n base conda
RUN conda install -c conda-forge netCDF4 threedigrid tqdm apscheduler folium qgrid line_profiler plotly rasterio pandas geopandas descartes websocket-client && \
      fix-permissions $CONDA_DIR
# python=3.7

RUN pip install --upgrade pip
RUN pip install threedi_scenario_downloader threedi_api_client jupyter_contrib_nbextensions && \
      fix-permissions /home/$NB_USER
# RUN pip install ipython=='7.1' pyproj=='1.9.6' jupyter_contrib_nbextensions threedi_scenario_downloader && \
#      fix-permissions /home/$NB_USER
      
#problems with projections in gdal3, when we downgrade proj to proj4 it works. 
RUN conda install proj4

# set password
RUN wget https://raw.githubusercontent.com/wietsevangerwen/docker/master/jupyter/jupyter_notebook_config.py -P /home/jovyan/.jupyter/

USER $NB_UID
