# The initial docker image to install all required packages. Installing the gdal package is quite cumbersome
# and therefore the image that is create with this image is used for further development. 

# Choose your desired base image 
# FROM jupyter/scipy-notebook:latest
FROM hhnk_jupyter3

USER root

#plotly dependencies - https://github.com/plotly/orca/issues/150
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        wget \
        xvfb \
        libgtk2.0-0 \
        libxtst6 \
        libxss1 \
        libgconf-2-4 \
        libnss3 \
        libasound2 && \
     mkdir -p /home/orca && \
     cd /home/orca && \
     wget https://github.com/plotly/orca/releases/download/v1.2.1/orca-1.2.1-x86_64.AppImage && \
     chmod +x orca-1.2.1-x86_64.AppImage && \
     ./orca-1.2.1-x86_64.AppImage --appimage-extract && \
     printf '#!/bin/bash \nxvfb-run --auto-servernum --server-args "-screen 0 640x480x24" /home/orca/squashfs-root/app/orca "$@"' > /usr/bin/orca && \
     chmod +x /usr/bin/orca
     
USER $NB_USER

# Install python3 libraries
# RUN conda install anaconda
RUN conda install -c conda-forge netCDF4 threedigrid tqdm apscheduler folium qgrid line_profiler plotly rasterio
RUN conda install -c conda-forge geopandas  && \
      fix-permissions $CONDA_DIR
# python=3.7

RUN pip install --upgrade pip threedigrid
RUN pip install ipython=='7.1' pyproj=='1.9.6' jupyter_contrib_nbextensions threedi_scenario_downloader && \
      fix-permissions /home/$NB_USER
      
# RUN jupyter contrib nbextension install #no permissions
      
# netCDF4 threedigrid tqdm apscheduler folium ipython=='7.1' qgrid

# openpyxl fiona==1.8a1 descartes xlrd xlwt && \
#    plotly lizard_connector 


# USER $NB_USER
