FROM tensorflow/tensorflow:2.0.0-py3-jupyter

USER root

# WORKDIR /workspace

# copy contents of repo to container
# COPY . /workspace

# install requirements
RUN pip install scikit-learn==0.20.2
RUN pip install joblib numpy glob2 tqdm pandas keras==2.3.1 requests

# define entrypoint
# ENTRYPOINT ["/workspace/run.sh"]
# RUN chmod +x /workspace/run.sh

# get model weights and input scaler
# RUN mkdir /workspace/data; exit 0
# RUN mkdir /workspace/models; exit 0
# RUN tar -zxvf rvw_models.tar.gz

# set password
RUN rm /home/jovyan/.jupyter/jupyter_notebook_config.py
RUN wget https://raw.githubusercontent.com/wvangerwen/docker/master/jupyter/jupyter_notebook_config.py -P /home/jovyan/.jupyter/

USER $NB_UID
